---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect Operating System
      ansible.builtin.command: "uname -s"
      register: os_type
      changed_when: false
      check_mode: no

    - name: Set platform variable
      ansible.builtin.set_fact:
        platform: "{{ 'macos' if os_type.stdout == 'Darwin' else 'wsl' }}"
      tags:
        - always

    - name: Import OS-specific tasks
      ansible.builtin.import_tasks: "pre_tasks/detect_{{ platform }}.yml"
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: "pre_tasks/whoami_{{ platform }}.yml"
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
