---
- name: Install ZSH and plugins
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting

- name: Copy zsh-autosuggestions and zsh-syntax-highlighting
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
    follow: yes  # Follow symbolic links
  loop:
    - "/opt/homebrew/Cellar/zsh-autosuggestions/*/share/zsh-autosuggestions/"
    - "/opt/homebrew/Cellar/zsh-syntax-highlighting/*/share/zsh-syntax-highlighting/"
  become: no
