---
- name: Run macOS Tasks
  ansible.builtin.import_tasks: macOS.yml
  when: ansible_os_family == 'Darwin'
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: "Zsh | Detect oh-my-zsh"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: ohmyzsh

- name: "Zsh | Install oh-my-zsh if not installed"
  when: not ohmyzsh.stat.exists
  block:
    - name: "Zsh | Download oh-my-zsh Install Script"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "{{ ansible_user_dir }}/oh-my-zsh.install.sh"
        mode: "0755"

    - name: "Zsh | Run oh-my-zsh Install Script"
      ansible.builtin.command:
        cmd: "sh {{ ansible_user_dir }}/oh-my-zsh.install.sh"

- name: Run ls command
  command: ls /path/to/src_directory

- name: "Zsh | Update .zshrc for all users"
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: "0644"
