---
- name: "Zsh | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: zsh_distribution_config

- name: "Zsh | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: zsh_distribution_config.stat.exists

- name: "Zsh | Detect oh-my-zsh"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: ohmyzsh

- name: "Zsh | Install oh-my-zsh if not installed"
  when: not ohmyzsh.stat.exists
  block:
    - name: "Zsh | Download oh-my-zsh Install Script"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "{{ ansible_user_dir }}/oh-my-zsh.install.sh"
        mode: "0755"

    - name: "Zsh | Run oh-my-zsh Install Script"
      ansible.builtin.command:
        cmd: "sh {{ ansible_user_dir }}/oh-my-zsh.install.sh"

- name: Clone zsh-syntax-highlighting repository
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1

- name: Add zsh-syntax-highlighting to .zshrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_user_dir }}/.zshrc"
    line: "source {{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

- name: Clone zsh-autosuggestions repository
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Add zsh-autosuggestions to .zshrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_user_dir }}/.zshrc"
    line: "source {{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"


- name: "Zsh | Update .zshrc for all users"
  ansible.builtin.copy:
    src: "roles/zsh/files/.zshrc"
    dest: "~/.zshrc"
    mode: "0644"
