---
- hosts: localhost
  connection: local
  gather_facts: no  # You might need this on if you use ansible facts

  tasks:
    - name: Detect Operating System
      command: "uname -s"
      register: os_type
      changed_when: false

    - name: Set platform variable
      set_fact:
        platform: "{{ 'macOS' if os_type.stdout == 'Darwin' else 'linux' }}"

    - name: Debug platform variable
      debug:
        var: platform

    - name: Include OS-specific tasks dynamically
      include_tasks: "pre_tasks/detect_{{ platform }}.yml"
      when: platform == 'macOS' or platform == 'ubuntu'
