---
- name: Detect Operating System
  ansible.builtin.command: "uname -s"
  register: os_type
  changed_when: false
  check_mode: no

- name: Include macOS-specific tasks dynamically
  ansible.builtin.include_tasks: macOS.yml
  when: os_type.stdout == 'Darwin'

- name: Include Ubuntu-specific tasks dynamically
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
